### ISSUE TITLE
Siri Shortcuts Not Working

### ISSUE THREAD

**Issue by Brmckenna95** [tnmendes/watt#118]
![IMG_1743](https://github.com/tnmendes/watt/assets/138815059/ce247f11-ca94-457a-9eed-a73912d46f55)

This is the error I keep getting.

**Comment by tnmendes** [comment]
Hey @Brmckenna95 what device model from Kasa do you have!? 

Is just one device that is happening this?

**Comment by Brmckenna95** [comment]
KP400 is the model number. I was able to find a workaround and created a
shortcut using the Kasa app.

**Comment by tnmendes** [comment]
This is happing because your plug has child plugs, at the moment it is not possible to add directly from the Watt app, however, you can add using the Apple Shortcuts App using the Watt app. There you will find your individual outlet name.

To do this just press the "+" button on the Shortcuts app
Press [Add Action]
Search for app Watt
Click "Change to On/Off your ..."
Select the state
Select the Device name (you will see your individual outlet name )


I am going close this issue because is related to this:
https://github.com/tnmendes/watt/issues/108

Thank you for the reporting

**Comment by Brmckenna95** [comment]
Technically, I tried doing that too but it gave me the same error.
