### ISSUE TITLE
Tapo P110

### ISSUE THREAD

**Issue by MindUpFr** [tnmendes/watt#42]
Hi,

congratulations for your great app !

Any idea about when you expect supporting the TAPO P110 plug ?

Best regards

Daniel

**Comment by tnmendes** [comment]
Hey @MindUpFr 

Thank you for the heads up, I didn't know the Tapo P110 was already on the market. 
I am going to try to order P110!!!

**Comment by tnmendes** [comment]
In the next 3 days should be out version 4.3 that will have support for P110

**Comment by MindUpFr** [comment]
Hi Tiago ,

Thank you for these great news !

I look forward testing it !

Regards,
Daniel

Le dim. 26 sept. 2021 à 20:24, Tiago Mendes ***@***.***> a
écrit :

**Comment by MindUpFr** [comment]
Hi Tiago,

Sorry if I disturb you, but I was wondering if there are any differences
between TAPO P110 and TP-Link HS110 ? Are they doing same things ?
It is just for me to know which one is best to buy ..

Thank you.
Regards,
Daniel

**Comment by tnmendes** [comment]
Hey Daniel, it's not an easy answer. The Kasa HS110 was replaced by the Kasa KP115. You can have a look here:
https://watt-app.com/blog-kasa-KP115.html

So if you already have products from one brand you should keep buying just from that brand.

If you don't have products from either of the two I recommend you select Tapo, because Tapo is a newer project and has a new team and you can see the difference between the Kasa app vs Tapo app...old design Vs new design.
