### ISSUE TITLE
Ability to password protect the device.

### ISSUE THREAD

**Issue by jaapajaa** [tnmendes/watt#5]
I use an air heat pump to heat the property.
The password option would prevent the pump from being shut down accidentally. 
(i have tp-link HS-110 enabled)

**Comment by tnmendes** [comment]
Instead of asking for a password, did it make sense to just send an alert asking if you are sure? 
To do like this:

![ezgif-5-0a8b295f550e](https://user-images.githubusercontent.com/9822076/72799234-aa3c3c00-3c3c-11ea-9996-202a73788a4c.gif)

I can add a flag to some devices then when activate do ask if you are sure

**Comment by jaapajaa** [comment]
OK That's fine!
Thank you!
