### ISSUE TITLE
Connector for ExoSense platform

### ISSUE THREAD

**Issue by smithdj5** [tnmendes/watt#99]
hi,

I realise this is off topic but I am impressed with how you have created an app that is linked into the TP-Link cloud.
I run an engineering consultancy company and we are involved in data collection from factories. We use a cloud app called ExoSense which connects to IoT devices. See [https://www.exosite.io/business/public/exchange/catalog?type=iot-connector]
It would be great if I could read data from the TP-link devices into this cloud.
Do you think you could write a "connector" for this task ?
If yes, I am willing to pay you a fee . Have a look at the link and let me know please ?

**Comment by tnmendes** [comment]
Hey @smithdj5, thank you for reaching out. As ExoSense is a company, I'm not sure if authorization from TP-Link is required. However, TP-Link appears to be open to such partnerships, as some configurations I've reviewed mention these partners: OhmConnect, Sapient Industries, Alexa Smart Energy, Samsung SmartThings, and Clova. This information was gathered from this API request: http://iot.tplinkra.com/1.0/sdk-config.

Since this topic is off-topic, I will close this discussion. If you'd like to continue to contact me, please use the email [voless.app@gmail.com](mailto:voless.app@gmail.com). Thank you!
